name: hydrationbuddy
description: "A simple water intake tracker app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.1
  flutter: 3.24.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  string_scanner: ^1.3.0
  test_api: ^0.7.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

